const article = el('article')
const button = el('button')
const div = el('div')
const form = el('form')
const h3 = el('h3')
const h4 = el('h4')
const header = el('header')
const input = el('input')
const img = el('img')

const click = on('click')