import { vnodeHTML } from '../src/index'

export const a = vnodeHTML('a')
export const article = vnodeHTML('article')
export const button = vnodeHTML('button')
export const div = vnodeHTML('div')
export const footer = vnodeHTML('footer')
export const h1 = vnodeHTML('h1')
export const h3 = vnodeHTML('h3')
export const h4 = vnodeHTML('h4')
export const header = vnodeHTML('header')
export const img = vnodeHTML('img')
export const input = vnodeHTML('input')
export const label = vnodeHTML('label')
export const li = vnodeHTML('li')
export const p = vnodeHTML('p')
export const span = vnodeHTML('span')
export const section = vnodeHTML('section')
export const strong = vnodeHTML('strong')
export const ul = vnodeHTML('ul')
