import { shorthand } from '../src/index'

export const a = shorthand('a')
export const article = shorthand('article')
export const button = shorthand('button')
export const div = shorthand('div')
export const footer = shorthand('footer')
export const h1 = shorthand('h1')
export const h3 = shorthand('h3')
export const h4 = shorthand('h4')
export const header = shorthand('header')
export const img = shorthand('img')
export const input = shorthand('input')
export const label = shorthand('label')
export const li = shorthand('li')
export const p = shorthand('p')
export const span = shorthand('span')
export const section = shorthand('section')
export const strong = shorthand('strong')
export const ul = shorthand('ul')
